# Generated by Django 6.0.7 on 2026-08-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('Development', 'Development'), ('QA', 'QA'), ('Staging', 'Staging'), ('Pre-Production', 'Pre-Production'), ('Production', 'Production')], max_length=30)),
                ('pipeline_name', models.CharField(max_length=100)),
                ('ci_provider', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('RUNNING', 'RUNNING')], max_length=20)),
                ('commit_sha', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=100)),
                ('triggered_by', models.CharField(max_length=100)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('build_url', models.URLField()),
            ],
        ),
    ]
