# Generated by Django 6.0.7 on 2026-08-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='deployment_version',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
